#!/bin/sh

export HOME="/afs/cern.ch/exp/totem/scratch/jkaspar"
export RFIO_USE_CASTOR_V2=YES
export STAGE_HOST=castorpublic
export STAGE_SVCCLASS=default
export SCRAM_ARCH='slc5_amd64_gcc434'
source "/afs/cern.ch/cms/cmsset_default.sh"
cd "/afs/cern.ch/work/j/jkaspar/software/offline/704/src"
eval `scram runtime -sh`

# EOS configuration
source "/afs/cern.ch/project/eos/installation/totem/etc/setup.sh"
shopt -s expand_aliases

function SafeCmd()
{
	echo ""
	echo ">> SafeCmd: $@"
	for i in {1..10}
	do
		echo "* attempt $i:"
		"$@" && return 0
		sleep 5
	done
	echo "* giving up..."
	return 1
}

# define directories
job_dir="$JOB_DIR"

(
# run the process
cd "$job_dir"

$COMMAND

) &> "$job_dir/$JOB_LOG_FILE"
