#!/bin/bash

# load EOS configuration
source "/afs/cern.ch/project/eos/installation/totem/etc/setup.sh"
shopt -s expand_aliases

runs=(
	"10322"
	"10324"
	"10325"
	"10326"
	"10327"
	"10328"
	"10329"
	"10331"
	"10332"
)

input_dir="/eos/totem/user/j/jkaspar/reco/alignment_sr"

for run in ${runs[*]}
do
	eos ls "$input_dir" | grep "run_${run}" | grep "_ntuple.root" | while read f
	do
		echo "	input_files.push_back(prefix + \"$f\");"
	done
done
